name: Metrics
on:
  # Schedule to run daily
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # General configuration
          user: shubhamtibra
          template: classic
          base: header, activity
          config_timezone: Asia/Kolkata
          
          # Plugin: Languages and code analysis
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # Plugin: Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit, pull_request
          
          # Plugin: Coding habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 8
          plugin_habits_charts: yes
          
          
          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 6
          
          
          # Plugin: Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Private contributions
          commits_authoring: subhamt@sprinto.com, subham.tibra@kommunicate.io
          repositories_affiliations: owner, collaborator
          repositories: 100
          repositories_skipped: ""
